### ISSUE TITLE
Adicionar novos campos no form de EXAM

### ISSUE THREAD

**Issue by diCaminha** [gladguys/easyteach#162]
Vai ser preciso de novas informações para EXAM:
- check para informar se a prova é de recuperação ou não
- informar o bimestre daquela prova (1, 2, 3 ou 4 bimestre).

restrições:
 - no input de bimestre, restringir apenas de 1 a 4
 - esses dois campos são obrigatórios

**Comment by diCaminha** [comment]
Para testar, subir a branch do PR: https://github.com/gladguys/aluco-api/pull/108

**Comment by diCaminha** [comment]
Verificar JSON no PR: https://github.com/gladguys/aluco-api/pull/108

**Comment by rodrigobastosv** [comment]
https://pub.dev/packages/numberpicker
