### ISSUE TITLE
Criar input de configurações (parâmetros) de turma

### ISSUE THREAD

**Issue by diCaminha** [gladguys/easyteach#173]
Vai ser preciso setar alguns parametros relacionado a turma:
- maximo numero de faltas
- valor minimo de media

Esses endpoints de configurações de turma foi implementado no PR 
https://github.com/gladguys/aluco-api/pull/120

obs 1: Não sei ainda se vai ser preciso criar uma tela inteira só pra isso;
obs 2: Essas informações tem q ser informadas no momento de criação de uma turma.

**Comment by rodrigobastosv** [comment]
@diCaminha essas informações vão poder ser editadas depois de criada a turma? Acho problemático se puderem...

**Comment by rodrigobastosv** [comment]
Alinhado com o @diCaminha que uma vez criado não pode ser editado
