### ISSUE TITLE
Sem redirecionamento ao criar usuario em SIGNUP

### ISSUE THREAD

**Issue by diCaminha** [gladguys/easyteach#188]
Quando clica em criar novo usuario, a request é feita pra API, porém deveria ser redirecionado para a tela de SIGN IN... em vez disso, não é informado nada ao usuário.

**Comment by rodrigobastosv** [comment]
Esta redirecionando! (ver gif no PR)

Não tinha é nenhuma notificação. Mas adicionei agora
