### ISSUE TITLE
Comportamento estranho da tela ao clicar em FAZER CHAMADA

### ISSUE THREAD

**Issue by diCaminha** [gladguys/easyteach#190]
Quando clico em FAZER CHAMADA na tela principal da turma a tela pisca duas vezes rapidamente antes de ir para a tela de chamadas.

Eu ohei esse comportamento nos outros módulos de turma e não acontece. Apenas quando clico em FAZER CHAMADA.

**Comment by rodrigobastosv** [comment]
Analisei isso aqui e não é bem um erro. Explicando um pouco da estrutura do app. Foi codado um loading interceptor que o papel dele é antes de toda chamada assincrona jogar um loading na tela e quando terminar fechar o loading. Entao o que ta acontecendo é que nesse endpoint acontece duas chamadas assincronas e o comportamento é esse
