### ISSUE TITLE
Fazer tela quadro de notas

### ISSUE THREAD

**Issue by rodrigobastosv** [gladguys/easyteach#96]
Mockup já tá feito (usar acordion)

- Parte da api já tá ok (branch: feature-students-grades )

ENDPOINT: api/classes/{id}/grades

**Comment by diCaminha** [comment]
`EXEMPLO DE JSON DE RETORNO`

[
    {
        "exams": [
            {
                "examId": 7,
                "examName": "VP3",
                "weight": 2,
                "studentId": null,
                "studentName": null,
                "grade": 9.5
            },
            {
                "examId": 8,
                "examName": "VP2",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": null
            },
            {
                "examId": 11,
                "examName": "VPX",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": 7.5
            }
        ],
        "average": "6.625",
        "studentName": "Denis Alcantra"
    },
    {
        "exams": [
            {
                "examId": 7,
                "examName": "VP3",
                "weight": 2,
                "studentId": null,
                "studentName": null,
                "grade": 10
            },
            {
                "examId": 8,
                "examName": "VP2",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": null
            },
            {
                "examId": 11,
                "examName": "VPX",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": 8.5
            }
        ],
        "average": "7.125",
        "studentName": "Diego Alcantra"
    },
    {
        "exams": [
            {
                "examId": 7,
                "examName": "VP3",
                "weight": 2,
                "studentId": null,
                "studentName": null,
                "grade": 10
            },
            {
                "examId": 8,
                "examName": "VP2",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": null
            },
            {
                "examId": 11,
                "examName": "VPX",
                "weight": 1,
                "studentId": null,
                "studentName": null,
                "grade": 5.5
            }
        ],
        "average": "6.375",
        "studentName": "Carlos Alcantra"
    }
]
